### ISSUE TITLE
How does the retrofit pagination would work in mosby ?

### ISSUE THREAD

**Issue by javajack** [sockeqwe/MosbyViewPagerDemo#2]
I am having hard time wrapping my head around the pagination part in this example.

What is the most appropriate way to pass on pagination parameter from MosbyActivity to Retrofit( probably via presenter ) and bring back paginated data ?

Right now retrofit is annotated with "/posts/all.json" which could have a valid "page" query parameter.

First time View pager gets populated with with page 1 data,
http://api.givesmehope.com/v1/posts/all.json?page=1

If user appeared at the last item in viewpager, mosby framework shall change the page=2 in retrofit and populate viewpager adapter data with response of following call.
http://api.givesmehope.com/v1/posts/all.json?page=2

Where to keep track of this "page" value in mosby framework and how to pass on that vale to retrofit ?

**Comment by sockeqwe** [comment]
The page value is part of the `View` since the view knows when he has reached the end of the list.

The `Presenter` should have 2 methods:
- `loadData()`:  Loads the first page on first app start, an shows a loading animation instead of view pager.
  - `loadMoreData(int page)`: Loads the given page.
    If the end has been reached the `View` should display a note that the next page is getting loaded on top of the viewpager (viewpager should remain visibile, but that just an UI / UX thing). That's what `presenter.loadMoreData(int page)` should do.

The View will have a method to addOlderData(List<Data>)` which should be merged together to a single list displayed in the view. Something like this:

``` java
interface MyView extends MvpLceView<List<GivesMeHopeElement>> {
     // inheritance alread brings showLoading(), showError(), showContent(), setData()

    showLoadingMoreData();
    showLoadingMoreError();
    setMoreData(List<GivesMeHopeElement> moreData);
}


class MyPresenter extends RetrofitPresenter {

     public void loadData(){
        api.getList(new LceCallback());
     }

    public void loadMoreData(int page){
        api.getList(page, new Callback<>(){
             // TODO call:
            // view.showLoadingMoreData()
           //  view. showLoadingMoreError()  
           // view. setMoreData()
          }
     }
}
```

If you want to work with `ViewState` then you have to write a custom view state (you could extend `CastedArrayListViewState`) to keep track that you are currently loading more data, so that after orientation changes you can come back to the "load more" state on your UI easily.

I'm working on a mail app sample, where I will implement pagination. Stay tuned.

**Comment by javajack** [comment]
Cool. Can I not create some kind of singleton which keep "page" object available inside mainactivity and presenter  using injection?

That way I could reuse the code written for existing view pager. Only retrofit parameter would change which would be refereed from this singleton.

Can we do it ? If yes how and Is it a good practice ?

**Comment by sockeqwe** [comment]
It may causes problems, because of Activity restart. If the activity restarts (for instance because another activity of your app has caused a crash) then your Activity with the viewpager also looses it's view state (everything is reseted, like starting for the first time), but the singleton may survive and  i.e. holds a value to the page with the numer 3, while the viewpager should load and display the first page.

I recomment to save the page number in your activity using `@Icicle` (Mosby ships with icepick, but you have to add [Icepick](https://github.com/frankiesardo/icepick) annotation processor into your build.gradle script with `apt` instead of `provided`)

**Comment by javajack** [comment]
I see.. I just implemented the singleton inside the module. It keeps track of the current page number.
I am testing the code on live device and experienced the very same thing as you described.

App was running in device, I run app from studio with some cosmetic changes, As I had implemented singleton, the singleton with page number was persisted and the API always started with second, third ( whichever ) page it was in.

You visualized it right, on that front. I am new to Android so i'll wrap my head around icepick in some time.

---

 I am using FragmentStatePagerAdapter as you have commented in the code.

One particular issue I observed is that view pager fragment is not rendered ( it gets kind of lost ) when app is not in foreground for a while and many apps are running in parallel.

In that case how do I restore the viewpager item, So that news item would be rendered always when app brought to foreground ?

**Comment by Akshay2693** [comment]
how can i use in interface for page count..
`
package com.example.trentium.MVC.model.api;

import com.example.trentium.MVC.model.utilities.cons;
import com.google.gson.GsonBuilder;

import retrofit.RestAdapter;
import retrofit.converter.GsonConverter;

/**
- Created by PCOM on 17-Oct-16.
  */
  public class Art_RestApiManager {
  private ArtsApi mArtApi;
  public ArtsApi getArtApi(int page,int totalitemcount) {
  
  ```
  if(mArtApi == null) {
      GsonBuilder gson = new GsonBuilder();
      gson.registerTypeAdapter(String.class, new StringDesirializer());
  
      mArtApi = new RestAdapter.Builder()
              //.setEndpoint(cons.BASE_URL+"/art/get_all_arts?page="+page)
              .setEndpoint(cons.BASE_URL)
              .setConverter(new GsonConverter(gson.create()))
              .build()
              .create(ArtsApi.class);
  }
  return mArtApi;
  ```
  
  }

}
/_for base url_/
`public static final String BASE_URL = "http://xyz/api/v1";`

/_for  fetch data..._/

 public void startFetching(int page , int totalItemCount) {

```
        mApiManager.getArtApi(page,totalItemCount).getArts1(page,new Callback<String>() {
            @Override
            public void success(String s, Response response) {

                Log.d(TAG, "JSON :: " + s);

                try {
                    JSONObject parentObject = new JSONObject(s);
                    JSONObject midobj = parentObject.getJSONObject("arts");
                    JSONArray parentArray = midobj.getJSONArray("list");

                    for (int i = 0; i < parentArray.length(); i++) {

                        JSONObject object = parentArray.getJSONObject(i);
                       /* Arts arts = new Arts.Builder()
                                .settitle(object.getString("title"))
                                .setprice(object.getDouble("price"))
                                .setdescription(object.getString("description"))
                                .setmain_image(object.getString("main_image"))
                                .setartist(object.getString("artist"))
                                .setart_id(object.getInt("art_id"))
                                .build();*/

                        mListener.onFetchProgress(arts);
                    }

                } catch (JSONException e) {
                    mListener.onFetchFailed();
                }
                mListener.onFetchProgress(mArts);
            }

            @Override
            public void failure(RetrofitError error) {
                Log.d(TAG, "Error :: " + error.getMessage());
                mListener.onFetchComplete();
            }
        });
    }
```

`
so how i put another place this method load page.. and callstartfetch( )method..

**Comment by sockeqwe** [comment]
I'm sorry, but I don't understand your question. Could you please rephrase your question and explain how that is related to mosby?

**Comment by Akshay2693** [comment]
actually i wants to make pagination onload with retrofit using recyclerview.. but i can't get it proper solution..
if u wants then i can send my code on your id..

**Comment by sockeqwe** [comment]
See my answer from above:
https://github.com/sockeqwe/MosbyViewPagerDemo/issues/2#issuecomment-93286967

Otherwise, please ask this kind of questions on stackoverflow.

**Comment by Akshay2693** [comment]
ok.. i done it can u tell me that how can i get this type of jsonArray data with retrofit2.0,
`{
  "status": true,
  "message": "",
  "arts": {
    "list": [
      {
        "artist": "Nehal",
        "art_id": "355",
        "title": "Test upload art",
        "description": "Large size shirt",
        "main_image": "http:\/\/xyz.com\/clients\/good\/assets\/images\/arts\/00cbbce7618444cd909b1e77ed213af51.jpg",
        "created_date": "14-09-2016",
        "price": "0.61",
        "status": "ACCEPTED",
        "size_description": "Large size shirt",
        "category": "Abstract Art",
        "size": "Large"
      },
      {
        "artist": "Nehal",
        "art_id": "354",
        "title": "Test dbfgbfhfghfhfhh",
        "description": "fghfghfghfghfghffghfg",
        "main_image": "http:\/\/xyz.com\/clients\/good\/assets\/images\/arts\/6.jpg",
        "created_date": "13-09-2016",
        "price": "0.39",
        "status": "ACCEPTED",
        "size_description": "Large size shirt",
        "category": "Shirt",
        "size": "Large"
      },`

here is my service generator class
`public class ServiceGenerator {

```
public static <S> S createService(Class<S> serviceClass) {

    OkHttpClient httpClient=new OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .build();

    GsonBuilder gson = new GsonBuilder();
    gson.registerTypeAdapter(String.class, new StringDesirializer());

    Retrofit retrofit = new Retrofit.Builder()
            .baseUrl("http://xyz.com/clients/good/api/v1/art/")
            .addConverterFactory(GsonConverterFactory.create())
            .client(httpClient).build();

    return retrofit.create(serviceClass);

}
```

}`

and here my interface 
`public interface newArtsApi {

```
@GET("/get_all_arts?page=")
Call<List<ArtsPagination>> getMovies(@Query("index") int index);`
```

I'm getting error for Jsonarray data parsing in retrofit 2.0... 
**Response Error for Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $**

so what is the changes i have to make ..?
